feat:add-detail-movie-page
newwavesolutions/flutter-base pull request #31
Opened 2023-06-19 10:44 UTC by hungtk-nws

2023-06-21 03:38 UTC, tuandqnws requested changes

2023-06-21 03:38 UTC, tuandqnws commented on lib/models/entities/movie_detail_entity.dart
> +
Kiểm tra lại các JsonKey(name) có đang thể hiện đúng tên trường trong JSON không

2023-06-21 03:38 UTC, tuandqnws commented on lib/repositories/movie_repository.dart
> +  Future<MovieDetailEntity> getDetailMovie({required int id}) {
Kết quả trả về của hàm Future cho phép nullable

2023-06-21 03:38 UTC, tuandqnws commented on lib/ui/pages/home/movies/movies_page.dart
> +              Get.to(() => MovieDetailPage(
Chuyển qua sử dụng Named Navigation

2023-06-21 03:38 UTC, tuandqnws commented on lib/ui/pages/movie_detail/movie_detail_page.dart
> +  final int id;
Tạo class MovieDetailArguments và pass data qua đó

2023-06-21 03:38 UTC, tuandqnws commented on lib/ui/pages/movie_detail/movie_detail_page.dart
> +            : Column(
Tách ra làm một method hoặc file riêng

2023-06-21 03:38 UTC, tuandqnws commented on lib/ui/pages/movie_detail/widgets/loading_movie_detail_widget.dart
> +    return const AppShimmer(
App Shimmer đã mặc định set width và height = double.infinity

2023-06-21 03:40 UTC, tuandqnws requested changes

2023-06-21 03:40 UTC, tuandqnws commented on lib/models/entities/movie_detail_entity.dart
> +  @JsonKey()
Kiểm tra lại các JsonKey(name) trong file có đang thể hiện đúng tên trường trong JSON không

2023-06-21 04:34 UTC, thoson-nws commented on lib/models/entities/movie_detail_entity.dart
> +class MovieDetailEntity {
MovieEntity

2023-06-21 04:35 UTC, thoson-nws commented on lib/models/entities/movie_detail_entity.dart
> +class MovieDetailEntity {
Bỏ đi

2023-06-21 04:35 UTC, thoson-nws requested changes
Sửa lại

2023-06-21 09:14 UTC, longtruongvan commented on lib/ui/pages/home/movie_detail/movie_detail_page.dart
> +      buildWhen: (previous, current) =>
tách nhỏ ra thành các hàm widget con

2023-06-30 04:11 UTC, thoson-nws approved these changes

2023-06-30 04:12 UTC, merged